### ISSUE TITLE
How to adjust the scale for sliders

### ISSUE THREAD

**Issue by buxiangzhiren** [DeepakSridhar/promptsliders#1]
Hi, thanks you for sharing the code!

I see the inference_sd.py only generate one image for the slider, can you tell me how to adjust the slider value to get different results?

**Comment by azmle112** [comment]
Same question, and when will the training code for Visual Prompt Slider be available?

**Comment by DeepakSridhar** [comment]
I added the inference code for sdxl with different scales [inference-promptsliders-sdxl.py](https://github.com/DeepakSridhar/promptsliders/blob/main/inference-promptsliders-sdxl.py)

Visual prompt slider should be straightforward if you follow the original concept sliders repository. I will try to release it later
